# Версия Docker Compose
version: "3.9"
services:
  php-apache:
    ports:
      # Проброс портов: хост:контейнер
      - "80:80"
    # Используем образ с именем "shamray7" и тегом "latest"  
    image: shamray7:latest
    volumes:
      # Привязка локальной директории "./www" к директории "/var/www/html" в контейнере
      - ./www:/var/www/html
  mysql:
    ports:
      # Проброс портов: хост:контейнер
      - "3306:3306"
    # Сборка образа MySQL с использованием Dockerfile из директории "./build/mysql"
    build: './build/mysql'
    environment:
      # Установка пароля для пользователя root
      MYSQL_ROOT_PASSWORD: "secret123"
      # Создание базы данных с именем "mifiib"
      MYSQL_DATABASE: "mifiib"
    volumes:
      # Привязка Docker Volume "dbData" к директории "/var/lib/mysql" в контейнере
      - dbData:/var/lib/mysql
volumes:
  # Создание Docker Volume с именем "www"
  www:
  # Создание Docker Volume с именем "dbData"
  dbData:
