#!bin/bash
####################################################################
############################| TASK#02 |#############################
#                           DESCRIPTION:                           
#            Script for backing up the /home directory, 
#      the config files of SSH, RDP, FTP, /var/log directory
#        Cron task to run this script every Friday at 18:30.
#    Move the backup to a separate pre-created /archive directory       
#-------------------------------------------------------------------
#               Written by Yuriy Shamray (aka Prospero)            
#                           MIFIIB - 2023                          
####################################################################
